### ISSUE TITLE
Posição dos badges do twitter e facebook quebradas

### ISSUE THREAD

**Issue by juliobetta** [teresinahc/peba#23]

**Comment by RuanAragao** [comment]
Acabei de fazer um push. Mas vendo no master, já existe uma correção para isso, apenas não está sendo compilada.

```
.facebook-like-button {
  border:none;
  overflow:hidden;
  height:21px;
  width:100px;
}
```

**Comment by juliobetta** [comment]
exatamente! rodei o production aqui na minha maquina e está normal.

**Comment by osanyin** [comment]
Implementado por @RuanAragao
