### ISSUE TITLE
Licença

### ISSUE THREAD

**Issue by marcelometal** [teresinahc/peba#25]
Olá, qual é a licença do projeto?

Também tenho projetos nessa linha de dados públicos e achei bem legal esse projeto. Quem sabe posso contribuir com algo.

Se a ideia é aceitar contribuições era bom deixar claro a licença, que tal adicionar uma arquivo LICENSE e também um cabeçalho nos arquivos?

Abração.

**Comment by osanyin** [comment]
Olá  @marcelometal! Primeiramente fico feliz em seu interesse por colaborar com o peba! A licença do peba é CC BY-SA. Infelizmente pecamos em não ter adicionado o arquivo LICENSE. Irei providenciar isso agora mesmo.

**Comment by marcelometal** [comment]
Eita, a CC BY-SA senão me engano não serve pra código...

**Comment by alexandreteles** [comment]
Não sedia melhor então, já que há o interesse no ShareAlike, que se usasse
a licença GPL ou AGPL?
Em 04/10/2015 22:33, "Marcelo Jorge Vieira" <notifications@github.com>
escreveu:

**Comment by osanyin** [comment]
Ela realmente não foi criada para isso, mas isso não a torna inutilizável para código. Mas com o feedback de vocês agora entendo a importância de usarmos outra licença :). O que acham de aplicarmos a GPL como sugeriu o @alexandreteles?

**Comment by marcelometal** [comment]
Tô chegando agora, mas qualquer licença de Software Livre ou Open Source me agradam.

No http://olhoneles.org utilizamos a AGPL.

http://www.gnu.org/licenses/why-affero-gpl.html

**Comment by alexandreteles** [comment]
Já fizeram um commit com a AGPL.
Em 05/10/2015 12:25, "Marcelo Jorge Vieira" <notifications@github.com>
escreveu:

**Comment by osanyin** [comment]
Bacana! Notei que a AGPL se adequa mais a esse tipo de software. Agradeço pela ajuda de vocês, ainda somos novos no mundo da colaboração open source, está sendo um aprendizado constante. :)

**Comment by DanLinus** [comment]
É importante esse lance de licenças!
